apiVersion: v1
kind: Service
metadata:
  name: grpc-server-svc
spec:
  ports:
  - name: grpc
    port: 8001
    targetPort: 8001
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: grpc-server-deploy
  type: LoadBalancer
