apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client-deploy
spec:
  template:
    spec:
      containers:
      - name: grpc-client-container
        resources:
          limits:
            cpu: 1024m
            memory: 1024Mi
          requests:
            cpu: 512m
            memory: 512Mi
